FROM node:12.13.0-alpine

# Create app directory
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install app dependencies
COPY package-lock.json package.json ./

RUN npm install

CMD npm start